### ISSUE TITLE
Invalid MEX-file 'M:\LeWoS matlab scripts\GCMex.mexw64': A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Rotoslider** [dwang520/LeWoS#2]
MEX file no longer works in Matlab 2022a Could you please update this. Your app looks to be a wonderful process. I would love to test.

**Comment by dwang520** [comment]
updated for windows os

**Comment by Rotoslider** [comment]
Invalid MEX-file 'C:\Users\me\AppData\Roaming\MathWorks\MATLAB Add-Ons\Apps\LeWoS\GCMex.mexw64': A dynamic link
library (DLL) initialization routine failed.
New computer. New install of Windows and Matlab 2022a. New download of LeWoS. Error is still there.
Loads point cloud. Starts running segmentation then the above error shows up after a few minutes. 

I get the following error first. I have 18 cores 36 threads. Only using 10. 
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 10).
Warning: Too many FOR loop iterations. Stopping after 9223372036854775806 iterations. 
Parallel pool using the 'local' profile is shutting down.

**Comment by Rotoslider** [comment]
Rebooted and tried again. Seems the mex64 error is now gone. So if anyone else gets this try to reboots and run it again. 
I still get the: Too many FOR loop iterations. Stopping after 9223372036854775806 iterations.  error.

**Comment by dwang520** [comment]
> Rebooted and tried again. Seems the mex64 error is now gone. So if anyone else gets this try to reboots and run it again.
> I still get the: Too many FOR loop iterations. Stopping after 9223372036854775806 iterations. error.

Hi, this isn’t an error. It’s just a warning message (I put a loop to infinite) and won’t affect the processing
